# Generated by Django 4.1.1 on 2022-10-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='login',
            field=models.CharField(max_length=30),
        ),
    ]
